# If you change this file in any major way, please bump the cache key version
# (grep for '!BUMP HERE!')

name: 'Setup Effekt Environment'
description: 'Sets up Java, Node, SBT, and system dependencies for Effekt'

inputs:
  java-version:
    description: 'Java version to install'
    required: false
    default: '11'
  node-version:
    description: 'Node version to install'
    required: false
    default: '16.x'
  llvm-version:
    description: 'LLVM version to install'
    required: false
    default: '18'
  install-dependencies:
    description: 'Whether to install system dependencies (Linux only)'
    required: false
    default: 'false'
  install-valgrind:
    description: 'Whether to install valgrind (Linux only)'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'zulu'
        cache: 'sbt'

    - name: Setup SBT
      uses: sbt/setup-sbt@v1

    - name: Set up NodeJS ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    # Cache system dependencies to avoid reinstalling them every time
    - name: Cache System Dependencies
      if: ${{ inputs.install-dependencies == 'true' && runner.os == 'Linux' }}
      id: cache-deps
      uses: actions/cache@v4
      with:
        path: |
          /usr/bin/chez*
          /usr/bin/scheme
          /usr/lib/llvm-${{ inputs.llvm-version }}
          /usr/bin/llvm*${{ inputs.llvm-version }}
          /usr/lib/x86_64-linux-gnu/libuv*
          /usr/include/uv*
        key: ${{ runner.os }}-${{ runner.arch }}-deps-llvm${{ inputs.llvm-version }}-v1 # !BUMP HERE!

    # Only run the following on Linux-based runners & if there's no cache miss
    - name: Update apt database
      if: ${{ inputs.install-dependencies == 'true' && runner.os == 'Linux' && steps.cache-deps.outputs.cache-hit != 'true' }}
      run: sudo apt-get update
      shell: bash

    - name: Install Chez Scheme
      if: ${{ inputs.install-dependencies == 'true' && runner.os == 'Linux' && steps.cache-deps.outputs.cache-hit != 'true' }}
      run: sudo apt-get install -y chezscheme
      shell: bash

    - name: Install LLVM ${{ inputs.llvm-version }}
      if: ${{ inputs.install-dependencies == 'true' && runner.os == 'Linux' && steps.cache-deps.outputs.cache-hit != 'true' }}
      run: sudo apt-get install -y llvm-${{ inputs.llvm-version }}
      shell: bash

    - name: Install libuv
      if: ${{ inputs.install-dependencies == 'true' && runner.os == 'Linux' && steps.cache-deps.outputs.cache-hit != 'true' }}
      run: sudo apt-get install -y libuv1-dev
      shell: bash

    - name: Install Valgrind
      if: ${{ inputs.install-valgrind == 'true' && runner.os == 'Linux' }}
      run: sudo apt-get install -y valgrind
      shell: bash
